biomes_tiles_layer = "CoreMod.MapBiomesTilesLayer"
biomes_layer = "CoreMod.GOLayer"
static_go_layer = "CoreMod.GOLayer"
nests_tiles_layer = "CoreMod.NestsTilesLayer"
nests_layer = "CoreMod.GOLayer"
tile_map_layer = "CoreMod.TileMapLayer"