MAP_HEIGHT = 32
MAP_WIDTH = 64
SPRITE_CHUNK_SIZE_X = MAP_WIDTH / 8
SPRITE_CHUNK_SIZE_Y = MAP_HEIGHT / 8
MAP_CONNECTIVITY = "Flat"
TILES_CONNECTIVITY = "Four"
SEED = 1488


BIOMES_GRAPHICS_LAYER = "graphics_layer"