MAP_HEIGHT = 16
MAP_WIDTH = 16
SPRITE_CHUNK_SIZE_X = 8
SPRITE_CHUNK_SIZE_Y = 8
MAP_CONNECTIVITY = "Flat"
TILES_CONNECTIVITY = "Four"
SEED = 1488

LAND_SURFACE = 0
OCEAN_SURFACE = 1

BIOMES_GRAPHICS_LAYER = "graphics_layer"
BIOMES_GO_LAYER = "biomes_layer"
STATIC_OBJECTS_LAYER = "static_go_layer"