MAP_HEIGHT = 32
MAP_WIDTH = 32
SPRITE_CHUNK_SIZE_X = 32
SPRITE_CHUNK_SIZE_Y = 32
MAP_CONNECTIVITY = "Flat"
TILES_CONNECTIVITY = "Four"
SEED = 128

LAND_SURFACE = 0
OCEAN_SURFACE = 1

BIOMES_GRAPHICS_LAYER = "graphics_layer"
BIOMES_GO_LAYER = "biomes_layer"
STATIC_OBJECTS_LAYER = "static_go_layer"


Equal = 0
NotEqual = 1
More = 2
Less = 3
MoreOrEqual = 4
LessOrEqual = 5